---
become_override: false
ocp_username: system:admin
silent: false

quickstart_deploy_make_directory: 

# Repository parameters
quickstart_deploy_make_repo_url: 
quickstart_deploy_make_branch: 



# Parameters passed to `make install` (key: value)
quickstart_deploy_make_params: