---
# become_override: false
# ocp_username: system:admin
# silent: false

# Git Clone parameters
quickstart_deploy_via_make_directory: 

# Repository parameters
quickstart_deploy_via_make_repo_url: 
quickstart_deploy_via_make_scm_ref: 


# Parameters passed to `make install` (key: value)
quickstart_deploy_via_make_params: []